# Generated by Django 5.2 on 2025-04-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialist', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
