# Generated by Django 5.2 on 2025-05-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_appointment_delete_hospital_remove_doctor_specialist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(max_length=100),
        ),
    ]
