# Generated by Django 5.2 on 2025-05-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_doctor_image_doctor_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image_url',
            field=models.ImageField(blank=True, max_length=2085, null=True, upload_to='doctor_images/'),
        ),
    ]
