# Generated by Django 5.2 on 2025-05-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_doctor_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image_url',
            field=models.CharField(blank=True, max_length=2085, null=True),
        ),
    ]
